include ~/.config/kitty/theme/theme.conf


font_family GeisstMono Nerd Font
font_size 13

shell:
  program: /bin/zsh
  args: ["--interactive"]

shell_intiegration no_cursor

cursor_shape block

cursor_stop_blinking_after 0
scrollback_lines 2000
copy_on_select yes
mouse_hide_wait 0
select_by_word_characters @-./_~?&=%+#a
enable_audio_bell no
disable_ligatures never

url_color
url_styl curly

remember_window_size  no
initial_winow_width 78c
initial_window_height 23c

window_border_width 1pt
draw_minimal_borders yes
window_padding_width 30
inactive_text_alpha 0.6
hide_window_decorations yes
confirm_os_window_close 0
tab_bar_style powerline
cursor_blink_interval 0

background_opacity 0.70

sync_to_monitor no

# BEGIN_KITTY_THEME



# END_KITTY_THEME
